-- begin BPMDEMO_ORDER
alter table BPMDEMO_ORDER add constraint FK_BPMDEMO_ORDER_ON_PERSON foreign key (PERSON_ID) references BPMDEMO_PERSON(ID)^
create index IDX_BPMDEMO_ORDER_ON_PERSON on BPMDEMO_ORDER (PERSON_ID)^
-- end BPMDEMO_ORDER
-- begin BPMDEMO_INSTRUMENT
alter table BPMDEMO_INSTRUMENT add constraint FK_BPMDEMO_INSTRUMENT_ON_ORDER foreign key (ORDER_ID) references BPMDEMO_ORDER(ID)^
create index IDX_BPMDEMO_INSTRUMENT_ON_ORDER on BPMDEMO_INSTRUMENT (ORDER_ID)^
-- end BPMDEMO_INSTRUMENT
