alter table BPMDEMO_INSTRUMENT add constraint FK_BPMDEMO_INSTRUMENT_ON_ORDER foreign key (ORDER_ID) references BPMDEMO_ORDER(ID);
create index IDX_BPMDEMO_INSTRUMENT_ON_ORDER on BPMDEMO_INSTRUMENT (ORDER_ID);
